name: vsc_acc
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  carousel_slider: ^4.2.1
  intl: ^0.20.1
  path_provider: ^2.1.5
  sqflite: ^2.4.1
  csv: ^5.0.1
  url_launcher: ^6.3.1
  flutter_email_sender: ^6.0.3
  file_picker: ^8.1.7
  permission_handler: ^11.3.1
  excel: ^4.0.6
  device_info_plus: ^11.2.1
  share_plus: ^10.1.4


dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  flutter_launcher_icons: ^0.14.2

flutter_icons:
  image_path: 'assets/images/vel.png'
  android: true
  ios: true

flutter:
  uses-material-design: true


  fonts:
   - family: Poppins-Light
     fonts:
       - asset: assets/fonts/Poppins-Light.ttf
   - family: Poppins-Medium
     fonts:
       - asset: assets/fonts/Poppins-Medium.ttf    
   - family: Poppins-Regular
     fonts:
       - asset: assets/fonts/Poppins-Regular.ttf   
   - family: Poppins-SemiBold
     fonts:
       - asset: assets/fonts/Poppins-SemiBold.ttf

  assets:
   - assets/images/


